### ISSUE TITLE
Consider reversing order of arguments.

### ISSUE THREAD

**Issue by jordwalke** [thizanne/ocaml-hamt#1]
Have you considered having the `t` argument be first in all of the operations? I believe this is consistent with Jane Street's core library and also makes it easier to bind the `t` to the functions which is more common than binding the other arguments IMHO.

**Comment by thizanne** [comment]
Changing the interface of Hamt would indeed make is consistent with Core, but then it would not be consistent anymore with the standard library interface of `Map` (to which it is aimed to offer an alternative), which also happens to be the convention of Batteries. I don't think there is One True Way to be preferred over the other one at the moment.

A better and more convincing solution for the second problem (which I believe is also the idea of Core) would probably be to offer a `Labelled` module. I would be very happy to merge a contribution which adds it (and will certainly do it myself eventually, but probably not in a short time, and only after other waiting improvements). Thanks for your input anyway, and as a side request, if you're using Hamt in a real code (which means something different of "let's add a lot of stuff and time it"), please consider contributing some way to have performance benchmarks on real situations.

**Comment by jordwalke** [comment]
I understand there's no one "true way" and neither convention is vastly better than the other. But while we're on the topic, wouldn't you agree that having the data come first in the arguments list is just _slightly_ better than the other way? Only based on my personal experience experimenting with OCaml so far, it seems I've had a small percentage more cases where it would have benefited me to have the data come first.

Either way, I think you're spot on that named arguments are what you do when you have anything resembling an opinion on the matter - they're unbiased w.r.t. currying priority! We should add that `Labelled` module similar to how there's the `Exceptionless` module.

I would probably give it a shot, but I don't feel confident since there's not a bunch of tests here and I have no clue what the best/desired convention for writing scalable tests in OCaml is.

**Comment by thizanne** [comment]
Having the data as the last argument allows to write something like this :

``` ocaml
data
|> map (( + ) 1)
|> filter (( > ) 2)
|> fold ( + ) 0
```

**Comment by jordwalke** [comment]
Great point.
