### ISSUE TITLE
consider using the CPU's popcount instruction via JaneStreet's Base

### ISSUE THREAD

**Issue by UnixJunkie** [thizanne/ocaml-hamt#2]
int_popcount from
https://github.com/janestreet/base/blob/dee8d637af902a92c739df7f3f8bc4d715c9d35d
/src/popcount.ml

If it really is performance critical.

**Comment by UnixJunkie** [comment]
Base.Popcount.int_popcount

**Comment by thizanne** [comment]
Although I obviously don't want to depend on Base for this lib, that could help. I'm keeping this open as a reminder when I have the time to do a long overdue refreshment of the whole lib.

**Comment by UnixJunkie** [comment]
@bobot just told me that zarith also have a popcount function.
That would be for sure a thinnier dependency to add.

**Comment by rgrinberg** [comment]
I gave this a try and it did absolutely nothing.
