### ISSUE TITLE
Remove might be buggy

### ISSUE THREAD

**Issue by thizanne** [thizanne/ocaml-hamt#3]
Originally reported by @g2p in rgrinberg/ocaml-hamt#5

Original report:

> I have code that contains the following:
> 
> ```
> let c1 = Hamt.String.cardinal !hamt in
> hamt := Hamt.String.remove key !hamt;
> let c2 = Hamt.String.cardinal !hamt in
> if succ c2 <> c1 then begin
>   Logs.info (fun m -> m "Removed one item, got %d -> %d" c1 c2);
>   failwith "remove bug"
> end
> ```
> 
> The assert is triggered, with messages such as: `Removed one item, got 2113 -> 2110`.
> Delta is in the 2-5 range.
> I'm using the predefined String HAMT.

**Comment by rgrinberg** [comment]
Fixed now.
